# Copyright 2020 the .NET Foundation
# Licensed under the MIT License

trigger:
- master

stages:
- stage: Build
  displayName: Check image build

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'

    - bash: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip3 install jupyter-repo2docker
      displayName: Install prereqs

    - bash: |
        jupyter-repo2docker --no-run .
      displayName: Test image build

